import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export async function generateStaticParams() {
    return [{ lang: 'en' }, { lang: 'es' }]
}

export default async function RootLayout({
                                             children,
                                             params,
                                         }: LayoutProps<'/[lang]'>) {
    return (
        <html lang={(await params).lang}>
        <body className="min-h-screen antialiased">{children}</body>
        </html>
    )
}